replicaCount: 1

image:
  repository: acrdevayu2026512.azurecr.io/spring-crud
  tag: "<tag>"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

mysql:
  host: mysql
  port: 3306
  database: <database-name>

keyVault:
  secrets:
    rootPassword:<secertID-from-azure>
